init:
  - cmd: SET PATH=C:\Python27;C:\Python27\Scripts;C:\python27-x64;%PATH%

install:
  - pip install pyinstaller
  
build_script:
  - pyinstaller -F TagTools.py
  - copy *.xml dist
  - copy Dependencies\*.exe dist
  
after_build:
  - 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=1024m -ms=on TagTools.7z .\dist\*
  
artifacts:
  - path: TagTools.7z
    name: TagTools
